import { test } from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { Miniflare, createFetchMock } from 'miniflare';
import { generateKeyPair, exportJWK, SignJWT } from 'jose';
import { authorizeAgent } from './oauth-client.mjs';

void test('Google users and their agents have isolated workspaces, including legacy data', async t => {
  const { privateKey, publicKey } = await generateKeyPair('RS256');
  const jwk = { ...await exportJWK(publicKey), kid: 'tenant-test' };
  const mock = createFetchMock(); mock.disableNetConnect();
  mock.get('https://www.googleapis.com').intercept({ path: '/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com' }).reply(200, { keys: [jwk] }).persist();
  const code = await build({ entryPoints: ['worker/index.ts'], bundle: true, write: false, format: 'esm', platform: 'browser', target: 'es2022' });
  const mf = new Miniflare({ modules: true, script: code.outputFiles[0].text, compatibilityDate: '2026-05-22', d1Databases: ['CAREER_DB'], bindings: { FIREBASE_PROJECT_ID: 'test-project' }, fetchMock: mock });
  t.after(() => mf.dispose());
  const sign = uid => new SignJWT({ email: uid+'@example.com', email_verified: true, auth_time: Math.floor(Date.now()/1000), firebase: { sign_in_provider: 'google.com' } }).setProtectedHeader({alg:'RS256',kid:'tenant-test'}).setSubject(uid).setIssuer('https://securetoken.google.com/test-project').setAudience('test-project').setIssuedAt().setExpirationTime('1h').sign(privateKey);
  const [a,b] = await Promise.all([sign('alice'),sign('bob')]);
  const send = (token,path,body) => mf.dispatchFetch('http://local/api/career/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  const ok = async (token,path,body) => { const r=await send(token,path,body);const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data; };
  const initial=await ok(a,'state');assert.equal(initial.profile.summary,'');
  // Disposable fixture: pre-login local records must never be assigned to a Google user.
  const db=await mf.getD1Database('CAREER_DB');
  await db.prepare('INSERT INTO records VALUES (?,?,?)').bind('jobs','legacy',JSON.stringify({id:'legacy',company:'Private legacy'})).run();
  await db.prepare('INSERT INTO meta VALUES (?,?)').bind('profile',JSON.stringify({summary:'Private legacy'})).run();
  assert.equal((await ok(b,'state')).jobs.length,0);
  await ok(a,'profile',{...initial.profile,summary:'Alice only',owner_uid:'bob'});
  assert.equal((await ok(b,'state')).profile.summary,'');
  const job={id:'same-id',company:'Alice Company',role:'Engineer',status:'关注中',priority:'普通'};
  await ok(a,'jobs',job);
  await ok(b,'jobs',{...job,company:'Bob Company'});
  assert.equal((await ok(a,'state')).jobs[0].company,'Alice Company');
  assert.equal((await ok(b,'state')).jobs[0].company,'Bob Company');
  const platform=(await ok(a,'state')).platforms[0];
  await ok(a,'platforms',{...platform,notes:'Alice private platform note'});
  assert.ok(!(await ok(b,'state')).platforms.some(p=>p.notes==='Alice private platform note'));
  const task=await ok(a,'tasks',{kind:'公司准备',jobId:'same-id'});
  assert.equal((await ok(b,'state')).tasks.length,0);
  assert.equal((await send(b,'import',{schemaVersion:1,completeTaskIds:[task.id]})).status,400);
  const material={id:'mat',jobId:'same-id',kind:'志望動機',title:'Private material',content:'Alice text',sourceNotes:'Fixture'};
  await ok(a,'import',{schemaVersion:1,materials:[material],completeTaskIds:[]});
  assert.equal((await ok(b,'state')).materials.length,0);
  assert.equal((await send(b,'attempts',{questionSetId:'alice-only',questionId:'q',language:'日语',answer:'x',durationSeconds:1})).status,400);
  const q={id:'q',title:'Question',questionJa:'質問',meaning:'Meaning',why:'Why',outline:'Outline',followUps:'Follow up',category:'Project',targetSeconds:60};
  await ok(a,'import',{schemaVersion:1,completeTaskIds:[],questionSets:[{id:'alice-only',jobId:'same-id',title:'Pack',scenario:'Scenario',plan:'Plan',sourceNotes:'Fixture',questions:[q]}],reports:[{id:'report',date:'2026-09-12',title:'Report',content:'Private report',sourceNotes:'Fixture'}]});
  const answer={questionSetId:'alice-only',questionId:'q',language:'日语',answer:'Private answer',durationSeconds:60};
  const attempt=await ok(a,'attempts',answer);
  assert.equal((await send(b,'attempts',answer)).status,400);
  const review={id:'review',attemptId:attempt.id};
  for(const field of ['summary','strengths','improvements','japaneseNotes','factChecks','revisedAnswer','followUps','nextPractice','sourceNotes'])review[field]='Fixture';
  assert.equal((await send(b,'import',{schemaVersion:1,completeTaskIds:[],reviews:[review]})).status,400);
  await ok(a,'import',{schemaVersion:1,completeTaskIds:[],reviews:[review]});
  const bob=await ok(b,'state');
  for(const field of ['questionSets','reports','attempts','reviews'])assert.equal(bob[field].length,0,field);
  const resumeEntry={id:'resume-same',kind:'employment',revision:0,data:{employer:'Alice employer',role:'Engineer'}};
  await ok(a,'resume',resumeEntry);
  assert.equal((await ok(b,'resume')).entries.length,0);
  assert.equal((await ok(b,'resume/history?id=resume-same')).entries.length,0);
  assert.equal((await send(b,'resume',{id:'result',kind:'achievement',revision:0,parentId:'resume-same',data:{title:'Cross account'}})).status,400);
  await ok(b,'resume',{...resumeEntry,data:{employer:'Bob employer',role:'Engineer'}});
  assert.equal((await ok(a,'resume')).entries[0].data.employer,'Alice employer');
  // Agents are admitted only through OAuth consent given by the signed-in owner.
  assert.equal((await send(undefined,'oauth/approve',{decision:'approve'})).status,401);
  const grant=await authorizeAgent(mf,{name:'Alice agent',scopes:['career:read'],approveHeaders:{Authorization:'Bearer '+a}});
  const issued={token:grant.issued.access_token,record:(await ok(a,'mcp/tokens')).tokens[0]};
  assert.equal(issued.record.name,'Alice agent');
  assert.equal((await ok(b,'mcp/tokens')).tokens.length,0);
  assert.equal((await send(b,'mcp/tokens/revoke',{id:issued.record.id})).status,400);
  assert.equal((await ok(issued.token,'state')).profile.summary,'Alice only');
  assert.equal((await send(issued.token,'resume',resumeEntry)).status,403);
  assert.equal((await send(issued.token,'profile',{revision:1,summary:'Overwrite'})).status,403);
  assert.equal((await send(issued.token,'mcp/tokens')).status,403);
  assert.equal((await send(issued.token,'oauth/approve',{decision:'approve'})).status,403);
  const rpc=async(token,method,params={})=>{
    const response=await mf.dispatchFetch('http://local/api/career/mcp',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});
    assert.equal(response.status,200,await response.clone().text());return response.json();
  };
  assert.ok((await rpc(issued.token,'initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}})).result.serverInfo);
  const listed=await rpc(issued.token,'tools/list');
  assert.ok(listed.result.tools.some(t=>t.name==='career_get_context'));
  assert.ok(!listed.result.tools.some(t=>t.name==='career_import'));
  assert.ok(listed.result.tools.some(t=>t.name==='career_get_resume'));
  assert.ok(!listed.result.tools.some(t=>t.name==='career_save_resume_entry'));
  const read=await rpc(issued.token,'tools/call',{name:'career_get_context',arguments:{}});
  assert.equal(JSON.parse(read.result.content[0].text).profile.summary,'Alice only');
  const writer={token:(await authorizeAgent(mf,{name:'Writer',scopes:['career:read','agent:write','career:write'],approveHeaders:{Authorization:'Bearer '+a}})).issued.access_token};
  const draft={id:'private-draft',revision:0,title:'Private management title',targetRole:'Backend',targetCompany:'Private target',language:'en',content:{name:'Public candidate',headline:'Engineer',summary:'Public summary',location:'',links:[],sections:[]},sourceRefs:[],privateNotes:'Secret evidence'};
  const draftWrite=await rpc(writer.token,'tools/call',{name:'career_save_personalized_resume',arguments:draft});
  assert.equal(draftWrite.result.isError,false);
  assert.equal((await ok(b,'personalized-resumes')).drafts.length,0);
  assert.equal((await send('', 'personalized-resumes')).status,401);
  assert.equal((await send(writer.token,'resume-publications',{draftId:draft.id,draftRevision:1,mode:'unlisted',expiresAt:''})).status,403);
  assert.equal((await send(b,'resume-publications',{draftId:draft.id,draftRevision:1,mode:'unlisted',expiresAt:''})).status,409);
  const pub=await ok(a,'resume-publications',{draftId:draft.id,draftRevision:1,mode:'unlisted',expiresAt:''});
  assert.equal((await send(b,'resume-publications/revoke',{id:pub.id})).status,404);
  const publicPage=await mf.dispatchFetch('http://local'+pub.path);
  assert.equal(publicPage.status,200);assert.ok(!(await publicPage.text()).includes('Secret evidence'));
  await ok(a,'resume-publications/revoke',{id:pub.id});
  assert.equal((await mf.dispatchFetch('http://local'+pub.path)).status,404);
  const contract=await rpc(writer.token,'tools/call',{name:'career_get_contract',arguments:{}});
  assert.match(contract.result.content[0].text,/schemaVersion/);
  const bundle={schemaVersion:1,completeTaskIds:[],reports:[{id:'mcp-report',date:'2026-09-12',title:'MCP report',content:'Saved through MCP',sourceNotes:'Fixture'}]};
  const preview=await rpc(writer.token,'tools/call',{name:'career_preview_import',arguments:{bundle}});
  assert.equal(preview.result.isError,false);
  assert.ok(!(await ok(a,'state')).reports.some(r=>r.id==='mcp-report'));
  const saved=await rpc(writer.token,'tools/call',{name:'career_import',arguments:{bundle}});
  assert.equal(saved.result.isError,false);
  assert.ok((await ok(a,'state')).reports.some(r=>r.id==='mcp-report'));
  assert.ok(!(await ok(b,'state')).reports.some(r=>r.id==='mcp-report'));
  const bad=await rpc(writer.token,'tools/call',{name:'career_import',arguments:{bundle:{...bundle,profile:{summary:'bad'}}}});
  assert.equal(bad.result?.isError ?? !!bad.error,true);
  await ok(a,'mcp/tokens/revoke',{id:issued.record.id});
  assert.equal((await send(issued.token,'state')).status,401);
  assert.equal(JSON.parse((await db.prepare("SELECT body FROM meta WHERE id='profile'").first()).body).summary,'Private legacy');
});
